### PR TITLE
Update astroport ANS to use incentives instead of generator

### PR DESCRIPTION
**Pull request by Buckram123**
Astroport added new contract `incentives` for staking, that replaces `generator` contract. 

- [x] Will open PR after testnets addresses gets updated as well, see: https://github.com/astroport-fi/astroport-changelog/issues/4

Closes ABS-335

### CODE REVIEW

**Comment by cyberhoward** [comment]
@Buckram123 bump

**Comment by Buckram123** [comment]
> @Buckram123 bump

I guess can't fetch it by my own, getting "Missing Authentication Token" from graphql.
@adairrr Can you fetch it with your authentication token?

**Comment by adairrr** [comment]
> > @Buckram123 bump
> 
> I guess can't fetch it by my own, getting "Missing Authentication Token" from graphql. @adairrr Can you fetch it with your authentication token?

Yep - was one of the reasons we did the manual api scraping here: https://github.com/AbstractSDK/abstract-name-service/pull/11

**Comment by cyberhoward** [comment]
Ok so can I just close this PR then?

**Comment by cyberhoward** [comment]
Or merge it

**Pull request merged**
